services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: streamgen-backend
    ports:
      - "8000:8000"
    cpus: 0.5
    environment:
      CAMERA_ENABLED: "${CAMERA_ENABLED:-0}"
      RECORD_OUTPUT_DIR: "/data/recordings"
    healthcheck:
      test:
        - "CMD"
        - "python3"
        - "-c"
        - "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=5)"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    
    restart: unless-stopped

    devices:
      - /dev/video0:/dev/video0
      - /dev/video1:/dev/video1           # keep if present; harmless if absent
      - /dev/media0:/dev/media0
      - /dev/media1:/dev/media1
      - /dev/media2:/dev/media2
      - /dev/media3:/dev/media3
    privileged: true
    
    group_add:
      - video

    volumes:
      - /run/udev:/run/udev:ro

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: streamgen-frontend
    ports:
      - "3000:80"
    cpus: 0.2
    depends_on:
      - backend
    restart: unless-stopped

  recorder:
    build:
      context: scripts
    container_name: streamgen-recorder
    depends_on:
      backend:
        condition: service_healthy
    command:
      - "--url"
      - "http://backend:8000/stream.mjpg"
      - "--output"
      - "/recordings/recording.mp4"
    volumes:
      - backend-recordings:/recordings
    restart: "no"

volumes:
  backend-recordings:
